#!/usr/bin/env python3
"""Generate the app's version stamp (app/lib/core/app_version.g.dart).

The app version is independent of the firmware targets: same app/lib content keeps the same
version, an edit mints a new one. Run it around a build (or in CI) before `flutter build`.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import version  # noqa: E402

OUT = os.path.join(version.ROOT, "app", "lib", "core", "app_version.g.dart")


def main():
    v = version.ensure_version("app")
    text = "// GENERATED by scripts/gen_app_version.py - do not edit.\n" \
           "const String kAppVersion = '%d.%d.%d.%d';\n" % (
               v["year"], v["month"], v["day"], v["iteration"])
    with open(OUT, "w") as f:
        f.write(text)
    print("app version %d.%d.%d.%d" % (v["year"], v["month"], v["day"], v["iteration"]))


if __name__ == "__main__":
    main()
