; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = Tamu_v2_0A

[env:DAS_v0_1]
build_type = release
platform = https://github.com/Community-PIO-CH32V/platform-ch32v
framework = noneos-sdk
board = genericCH32V003F4P6
board_build.stack_size = 576
upload_protocol = minichlink
debug_tool = minichlink
build_flags = 
	-Os
	-flto
	-ffunction-sections
	-fdata-sections
	-fno-unwind-tables
	-fno-exceptions
	-D BOARD_DAS_v0_1
	-D STORAGE_FLASH_SIZE=2048
	-D STORAGE_BLOCK_SIZE=64
	-D MEMORY_BACKUP_CAP=256
	-D NUMBER_ONLY_32BIT
	-D USE_REGISTER_SERVICE
	-D DISABLE_DYNAMIC_MEMORY
	-D DISABLE_KEYED_MEMORY
	-Wno-unused-function
	-Wl,--section-start=.fixed_data=0x3800
	-Wl,--gc-sections
monitor_speed = 115200

[env:Tamu_v2_0A]
build_type = release
platform = espressif32
framework = espidf
board = esp32-c3-devkitc-02
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_build.partitions = partitions.csv
build_flags = 
	-D BOARD_Tamu_v2_0A
	-D TYPE_CORE
	-D USE_DYNAMIC_MEMORY
	-D USE_KEYED_MEMORY
	-D USE_APP_INTERFACE
	-D STORAGE_FLASH_SIZE=0xED000
	-D CONFIG_ESP_CONSOLE_UART_CUSTOM=y
	-Wno-error=old-style-declaration
    -Wno-error=c++-compat
	-Wno-error=missing-field-initializers
monitor_dtr = 0
monitor_rts = 0
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:Tamu_v1_0]
build_type = release
platform = espressif32
board = esp32dev
lib_deps = 
	fastled/FastLED
	madhephaestus/ESP32Servo
board_build.flash_mode = qio
board_build.partitions = .csv
board_build.flash_size = 4MB
build_flags = 
	-D BOARD_Tamu_v1_0
	-D USE_FIXED_POINT=0
monitor_dtr = 0
monitor_rts = 0
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
